#!/usr/bin/env bash

echo "Pushing"
git push

echo "Dump Database"
mysqldump -u root -ptomanik685secure mapas > deploy.dump
echo 'update settings SET api_google="ABQIAAAAZQVvkUMmHSU48Y8mCjnWMhSMZKSkciUzkpujvqVT6p77iOR9_BS1pnqTQC3G1H4JBbj9xzN2WF9ukA";' >> deploy.dump

echo "Sending dump to remote host"
scp deploy.dump amazon:/var/www/deploy.dump

echo "Performing remote tasks"
ssh amazon 'mysqldump -u root -ptomanik685secure mapas > /var/www/lastbkp;cd /var/www;git pull;mysql -u root -ptomanik685secure -D mapas < /var/www/deploy.dump; rm -Rf /var/www/application/cache/*'

echo "Cleaning"
rm deploy.dump
