#!/usr/bin/env bash

echo "Pushing"
git push

echo "Sending dump to remote host"
scp deploy.dump mapas:/home/mapascom/public_html/mapas/

echo "Performing remote tasks"
ssh mapas 'cd /home/mapascom/public_html/mapas/;git pull;rm -Rf /home/mapascom/public_html/mapas/application/cache/*'
