#!/usr/bin/env bash

echo "Pushing"
#git push

echo "Dump Database"
mysqldump -u root -ptomanik685secure mapas > deploy.dump

echo "Sending dump to remote host"
scp deploy.dump pika@pokedex.local:/Applications/MAMP/htdocs/mapas

echo "Performing remote tasks"
ssh mapas 'mysqldump -u mapas -psecure_tailorbirds_685 mapas > /Applications/MAMP/htdocs/mapas/lastbkp;cd /Applications/MAMP/htdocs/mapas;git pull;mysql -u mapas -psecure_tailorbirds_685 -D mapas < /Applications/MAMP/htdocs/mapas/deploy.dump;rm -Rf /Applications/MAMP/htdocs/mapas/application/cache/*'

echo "Cleaning"
rm deploy.dump
