ALTER TABLE incident ADD COLUMN owner_id INTEGER DEFAULT NULL
ALTER TABLE incident_kml ADD COLUMN owner_id INTEGER DEFAULT NULL
ALTER TABLE location ADD COLUMN owner_id INTEGER DEFAULT NULL
ALTER TABLE location_layer ADD COLUMN owner_id INTEGER DEFAULT NULL
ALTER TABLE media ADD COLUMN owner_id INTEGER DEFAULT NULL
ALTER TABLE layer ADD COLUMN owner_id INTEGER DEFAULT NULL
